// ************************************************************************************************
//   Custom DPA Handler code example - Shows custom (un)bonding and factory settings using button *
// ************************************************************************************************
// Copyright (c) IQRF Tech s.r.o.
//
// File:    $RCSfile: CustomDpaHandler-Bonding.c,v $
// Version: $Revision: 1.39 $
// Date:    $Date: 2020/01/03 13:56:50 $
//
// Revision history:
//   2019/12/11  Release for DPA 4.11
//   2019/10/09  Release for DPA 4.10
//   2019/06/03  Release for DPA 4.02
//   2019/01/10  Release for DPA 4.00
//   2018/10/25  Release for DPA 3.03
//   2017/08/14  Release for DPA 3.01
//   2017/03/13  Release for DPA 3.00
//   2015/08/05  Release for DPA 2.20
//
// *********************************************************************

// Online DPA documentation https://doc.iqrf.org/DpaTechGuide/

// Default IQRF include (modify the path according to your setup)
#include "IQRF.h"

// Default DPA header (modify the path according to your setup)
#include "DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "DPAcustomHandler.h"

// This code illustrates bonding using a button connected to the custom pin.
// Except going to sleep the code behaves the same way as the standard bonding procedure.
// Please see https://www.iqrf.org/DpaTechGuide/index.html?page=device-startup.html and the following chapters.

// Define to just reassign a bonding button with the button behavior implemented inside DPA
// #define	USE_DpaEvent_BondingButton

// Custom bonding button. Change to the pin and an active level of your choice.
//#define	IsButton  ( !PORTA.5 )
#define	IsButton  buttonPressed

// Returns TRUE when button is released shortly after LEDG goes out
bit ButtonAfterGreen();
// Same as above but with leading gap
bit ButtonAfterGreenWithGap();
// RedLED on for 1s 
void LEDR1s();

// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
bit CustomDpaHandler()
//############################################################################################
{
  // Handler presence mark
  clrwdt();

  // Detect DPA event to handle
  switch ( GetDpaEvent() )
  {
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the “empty” return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.
      return Carry;

#ifdef USE_DpaEvent_BondingButton
      // -------------------------------------------------
    case DpaEvent_BondingButton:
      // Called to allow a bonding button customization 

      userReg1.0 = 0;
      if ( IsButton )
        userReg1.0 = 1;

      return TRUE;
#else
      // -------------------------------------------------
    case DpaEvent_Reset:
      // Called after module is reset

      // Handle (un)bonding
      if ( !amIBonded() )
      {
        // -------------------------------------------------
        // Not bonded

        // Very 1st bonding attempt and well released button after 2.5 s gap and LEDG?
        if ( ButtonAfterGreenWithGap() )
          // Factory settings!
          goto _factoryAndRemoveBond;

        // If and while node is not bonded
        for ( ;; )
        {
          // If button is not pressed, be ready to be SmartConnected
          while ( !IsButton )
          {
            // Do and wait for an indication
            pulseLEDR();
            waitMS( 6 );
            // Make sure to use LP mode
            setRFmode( _WPE | _RX_LP | _TX_LP );

            // Set sometimes a new service channel for SmartConnect, otherwise the last one
            static uns8 lastServiceChannel;
            static uns8 channelCnt;
            // Time to set a new service channel?
            if ( ( channelCnt & 0x03 ) == 0 )
              // Set a new service channel
              lastServiceChannel = 0;
            // Next "timer"
            channelCnt++;

            // Set the SmartConnect service channel
            setServiceChannel( lastServiceChannel );
            // Save last service channel used
            lastServiceChannel = param2 + 1;

            // Try SmartConnect
            _checkRFcfg_PQT = TRUE;
            toutRF = 6;
            RFRXpacket();
            answerSystemPacket();
            // Restore RF settings (and make sure Spirit1 is not locked)
            wasRFICrestarted();
            DpaApiSetRfDefaults();
            // SmartConnect success?
            if ( amIBonded() )
              goto _NodeWasBonded;
          }

          // Bonding by button indication
          pulseLEDR();
          // Traditional bonding using 3 service channels
          _3CHTX = TRUE;
          // Bonded?
          if ( bondRequestAdvanced() )
          {
_NodeWasBonded:
            // Indicate bonding for 0.5 s
            setLEDG();
            waitDelay( 50 );
            stopLEDG();
            // Exit the loop
            break;
          }
        }
      }
      else
      {
        // -------------------------------------------------
        // Bonded

        // If the button is pressed for 2s (Green LED is on during this time) and then released within 0.5s, then un-bond the node (indicated by 1s Red LED)
        if ( ButtonAfterGreen() )
        {
          // Red LED for 1s
          LEDR1s();
          // Remove bond + implicit restart
          _DpaDataLength = 0;
          _PNUM = PNUM_NODE;
          _PCMD = CMD_NODE_REMOVE_BOND;
          // Perform local DPA Request
          DpaApiLocalRequest();
          // Unreachable code because of restart
        }

        // Now wait if the button is still pressed for about 2.5 s and if again released after green LED do factory settings and remove bond
        if ( ButtonAfterGreenWithGap() )
        {
_factoryAndRemoveBond:
          // Red LED for 1s
          LEDR1s();
          // Factory settings + remove bond + implicit restart
          _DpaDataLength = 0;
          _PNUM = PNUM_OS;
          _PCMD = CMD_OS_FACTORY_SETTINGS;
          // Perform local DPA Request
          DpaApiLocalRequest();
          // Unreachable code because of restart
        }
      }

      return TRUE;
#endif
  }

  return FALSE;
}

//############################################################################################
void LEDR1s()
//############################################################################################
{
  setLEDR();
  waitDelay( 100 );
  stopLEDR();
}

//############################################################################################
bit ButtonAfterGreen()
//############################################################################################
{
  // Returns TRUE when button is released shortly after LEDG goes out

  // Time for Green LED on
  startDelay( 200 );
  // Green LED on
  setLEDG();
  do
  {
    // If button not pressed
    if ( !IsButton )
    {
      // Switch off Green LED
      stopLEDG();
      // And return FALSE
      return FALSE;
    }
    // Is button still pressed while Green LED is on?
  } while ( isDelay() );

  // Switch off Green LED
  stopLEDG();
  // Set testing delay
  startDelay( 50 );
  do
  {
    // If the button is released within the delay
    if ( !IsButton )
      // Return TRUE
      return TRUE;
  } while ( isDelay() );
  // Otherwise return FALSE
  return FALSE;
}

//############################################################################################
bit ButtonAfterGreenWithGap()
//############################################################################################
{
  // Is button pressed for 2.55s ?
  startDelay( 255 );
  while ( IsButton && isDelay() );
  // If not the next call will return FALSE, otherwise will test for button release after Green LED goes off
  return ButtonAfterGreen();
}

//############################################################################################
// Default Custom DPA Handler header; 2nd include to implement Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup) 
#include "DPAcustomHandler.h"
//############################################################################################
