// *********************************************************************
//   Custom DPA Handler code example - HW peripheral memory mapping    *
// *********************************************************************
// Copyright (c) IQRF Tech s.r.o.
//
// File:    $RCSfile: CustomDpaHandler-LED-MemoryMapping.c,v $
// Version: $Revision: 1.21 $
// Date:    $Date: 2020/01/03 13:56:50 $
//
// Revision history:
//   2018/10/25  Release for DPA 3.03
//   2017/03/13  Release for DPA 3.00
//   2015/08/05  Release for DPA 2.20
//   2014/10/31  Release for DPA 2.10
//   2014/07/26  Release for DPA 2.01
//
// *********************************************************************

// Online DPA documentation https://doc.iqrf.org/DpaTechGuide/

// The application demonstrates memory mapping of the actual MCU peripheral to the DPA RAM peripheral
// byte @ PeripheralRam[0] = controls red LED
// byte @ PeripheralRam[1] = controls green LED
//
// bytes @ PeripheralRam[0..1]
//   0: LED off
//   1: LED on
//   2: LED pulse
//   3: LED pulsing
//   other: no change

// Default IQRF include (modify the path according to your setup)
#include "IQRF.h"

// Default DPA header (modify the path according to your setup)
#include "DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "DPAcustomHandler.h"

// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
bit CustomDpaHandler()
//############################################################################################
{
  // Handler presence mark
  clrwdt();

  // Detect DPA event to handle (unused event handlers can be commented out or even deleted)
  switch ( GetDpaEvent() )
  {
#ifdef DpaEvent_Interrupt
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the “empty” return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.

      return Carry;
#endif

      // -------------------------------------------------
    case DpaEvent_Notification:
      // Called after DPA request was processed and after DPA response was sent

      // Anything written to the RAM?
      // (could be optimized by checking the RAM address that was written to and based on its value control the appropriate LED)
      if ( _PNUM == PNUM_RAM && _PCMD == CMD_RAM_WRITE )
      {
        // Control red LED
        switch ( PeripheralRam[0] )
        {
          // Switch the LED off
          case 0:
            stopLEDR();
            break;

            // Switch the LED on (first make sure that the optional pulsing is disabled)
          case 1:
            setLEDR();
            // Make sure LED is visible at LP mode
            waitMS( 20 );
            break;

            // Make one pulse
          case 2:
            pulseLEDR();
            // Make sure LED is visible at LP mode
            waitMS( 20 );
            break;

            // Start pulsing
          case 3:
            pulsingLEDR();
            break;
        }

        // Control green LED
        switch ( PeripheralRam[1] )
        {
          // Switch the LED off
          case 0:
            stopLEDG();
            break;

            // Switch the LED on (first make sure that the optional pulsing is disabled)
          case 1:
            setLEDG();
            // Make sure LED is visible at LP mode
            waitMS( 20 );
            break;

            // Make one pulse
          case 2:
            pulseLEDG();
            // Make sure LED is visible at LP mode
            waitMS( 20 );
            break;

            // Start pulsing
          case 3:
            pulsingLEDG();
            break;
        }
      }

      break;
  }

  return FALSE;
}
//############################################################################################
// Default Custom DPA Handler header; 2nd include to implement Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup)
#include "DPAcustomHandler.h"
//############################################################################################
