// *********************************************************************
//   Custom DPA Handler code example - UART repeater                   *
// *********************************************************************
// Copyright (c) IQRF Tech s.r.o.
//
// File:    $RCSfile: CustomDpaHandler-UARTrepeater.c,v $
// Version: $Revision: 1.24 $
// Date:    $Date: 2020/01/03 13:56:50 $
//
// Revision history:
//   2019/12/11  Release for DPA 4.11
//   2018/10/25  Release for DPA 3.03
//   2017/03/13  Release for DPA 3.00
//   2016/09/12  Release for DPA 2.28
//   2015/08/05  Release for DPA 2.20
//   2014/10/31  Release for DPA 2.10
//
// *********************************************************************

// Online DPA documentation https://doc.iqrf.org/DpaTechGuide/

// Default IQRF include (modify the path according to your setup)
#include "IQRF.h"

// Default DPA header (modify the path according to your setup)
#include "DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "DPAcustomHandler.h"

// This example opens its UART peripheral and periodically TX data previously RX from UART, the data are available at peripheral RAM too
// This example works only at STD mode, not at LP mode

// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
bit CustomDpaHandler()
//############################################################################################
{
  // Handler presence mark
  clrwdt();

  // Detect DPA event to handle
  switch ( GetDpaEvent() )
  {
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the “empty” return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.

DpaHandleReturnTRUE:
      return TRUE;

      // -------------------------------------------------
    case DpaEvent_Idle:
      // Do a quick background work when RF packet is not received

      // No data RX from UART yet
      _DpaDataLength = 0;
      for ( ;; )
      {
        // TX and RX data to/from UART
        _PNUM = PNUM_UART;
        _PCMD = CMD_UART_WRITE_READ;
        // Wait 0 ms for RX
        _DpaMessage.PerUartSpiWriteRead_Request.ReadTimeout = 0;
        // Copy previously RX data to TX
        copyMemoryBlock( PeripheralRam + offsetof( TPerUartSpiWriteRead_Request, WrittenData ), _DpaMessage.PerUartSpiWriteRead_Request.WrittenData, _DpaDataLength );
        // One more byte to the request
        _DpaDataLength++;
        // TX/RX from UART
        DpaApiLocalRequest();
        // Error TX/RX UART?
        if ( _PNUM == PNUM_ERROR_FLAG )
        {
          setLEDR();
          break;
        }

        // No data RX?
        if ( _DpaDataLength == 0 )
          break;

        // Indicate RX data
        pulseLEDG();
        // Copy to RAM peripheral RX data length and ...
        PeripheralRam[0] = _DpaDataLength;
        // RX data too
        copyMemoryBlock( _DpaMessage.Response.PData, PeripheralRam + 1, _DpaDataLength );
      }
      break;
  }

  return FALSE;
}
//############################################################################################
// Default Custom DPA Handler header; 2nd include to implement Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup) 
#include "DPAcustomHandler.h"
//############################################################################################
