// ********************************************************************************
//   Custom DPA Handler code example - Intercepting DPA request and DPA responses *
// ********************************************************************************
// Copyright (c) IQRF Tech s.r.o.
//
// File:    $RCSfile: CustomDpaHandler-HookDpa.c,v $
// Version: $Revision: 1.25 $
// Date:    $Date: 2020/01/03 13:56:50 $
//
// Revision history:
//   2017/03/14  Release for DPA 3.00
//   2015/08/05  Release for DPA 2.20
//   2014/10/31  Release for DPA 2.10
//   2014/04/30  Release for DPA 2.00
//
// ********************************************************************************

// Online DPA documentation https://doc.iqrf.org/DpaTechGuide/

// Default IQRF include (modify the path according to your setup)
#include "IQRF.h"

// Uncomment to implement Custom DPA Handler for Coordinator
//#define COORDINATOR_CUSTOM_HANDLER

// Default DPA header (modify the path according to your setup)
#include "DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "DPAcustomHandler.h"

// This example show advance techniques intercepting DPA requests and responses
// This example works only at STD mode, not at LP mode

// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
bit CustomDpaHandler()
//############################################################################################
{
  // Handler presence mark
  clrwdt();

  // Detect DPA event to handle
  switch ( GetDpaEvent() )
  {
#ifdef DpaEvent_Interrupt
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the “empty” return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.

      return Carry;
#endif

      // -------------------------------------------------
    case DpaEvent_ReceiveDpaRequest:
      // Called after DPA request was received

      // Do not allow request from Interface
      if ( TX == LOCAL_ADDRESS )
      {
        DpaApiSetPeripheralError( ERROR_NADR );

ReturnFromRequestError:
        _PCMD |= RESPONSE_FLAG;
        return TRUE;
      }

      // If LEDR is ON, then write protect RAM peripheral by returning ERROR_FAIL
      if ( _PNUM == PNUM_RAM && _PCMD == CMD_RAM_WRITE && _LEDR == 1 )
      {
        DpaApiSetPeripheralError( ERROR_FAIL );
        goto ReturnFromRequestError;
      }

      break;

      // -------------------------------------------------
    case DpaEvent_BeforeSendingDpaResponse:
      // Called before sending DPA response back to originator of DPA response

      // If LEDG is ON, then add +1 to all read bytes from RAM peripheral
      if ( _PNUM == PNUM_RAM && _PCMD == CMD_RAM_READ && _LEDG == 1 )
      {
        FSR0 = _DpaMessage.Response.PData - 1;
        uns8 loop = _DpaDataLength;
        do
        {
          setINDF0( *++FSR0 + 1 );
        } while ( --loop != 0 );
      }

      break;
  }

  return FALSE;
}
//############################################################################################
// Default Custom DPA Handler header; 2nd include to implement Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup) 
#include "DPAcustomHandler.h"
//############################################################################################
