// *********************************************************************
//   Custom DPA Handler code example - Using TMR6 MCU timer            *
// *********************************************************************
// Copyright (c) IQRF Tech s.r.o.
//
// File:    $RCSfile: CustomDpaHandler-Timer.c,v $
// Version: $Revision: 1.35 $
// Date:    $Date: 2020/02/20 17:18:58 $
//
// Revision history:
//   2017/03/13  Release for DPA 3.00
//   2016/09/12  Release for DPA 2.28
//   2015/08/05  Release for DPA 2.20
//   2014/10/31  Release for DPA 2.10
//   2014/04/30  Release for DPA 2.00
//
// *********************************************************************

// Online DPA documentation https://doc.iqrf.org/DpaTechGuide/

// Default IQRF include (modify the path according to your setup)
#include "IQRF.h"

// Default DPA header (modify the path according to your setup)
#include "DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "DPAcustomHandler.h"

// This example initializes TMR6 (at Reset or Init event) and uses it to pulse LED at Idle event.
// TMR6 if driven by the internal PIC RC oscillator. See CustomDpaHandler-TimerCalibrated.c for a more precise timer implementation.
// This example works only at STD mode, not at LP mode

// If next symbol is defined then initialize timer at Reset event so it could be used already during Reset events (custom un/bonding)
//#define	EARLY_INITIALIZATION

// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
bit CustomDpaHandler()
//############################################################################################
{
  // Handler presence mark
  clrwdt();

  // Place for local static variables used only within CustomDpaHandler() among more events
  static uns8 tmrCounter;

  // Detect DPA event to handle
  switch ( GetDpaEvent() )
  {
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the “empty” return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.

      //  If TMR6 interrupt occurred
      if ( TMR6IF )
      {
        // Unmask interrupt
        TMR6IF = 0;
        // Decrement count
        if ( tmrCounter != 0 )
          tmrCounter--;
      }

      return Carry;

      // -------------------------------------------------
    case DpaEvent_Idle:
      // Do a quick background work when RF packet is not received

      if ( tmrCounter == 0 )
      {
        // Pulse LEDR every 1.0 s
        tmrCounter = 1000 / 10;
        pulseLEDG();
      }

      break;

      // -------------------------------------------------
#ifdef EARLY_INITIALIZATION
    case DpaEvent_Reset:
      // Called after module is reset
      // Could be called more times, but initialize Timer only once
      if ( !TMR6IE )
#else
    // -------------------------------------------------
    case DpaEvent_Init:
      // Do a one time initialization before main loop starts
#endif
    {
      // Setup TMR6 to generate ticks on the background (ticks every 10ms)
#if F_OSC == 16000000
      PR6 = 250 - 1;
      T6CON = 0b0.1001.1.10;	// Prescaler 16, Postscaler 10, 16 * 10 * 250 = 40000 = 4MHz * 10ms
#else
#error Unsupported oscillator frequency
#endif

      TMR6IE = TRUE;
    }
    break;

    // -------------------------------------------------
    case DpaEvent_AfterSleep:
      // Called on wake-up from sleep
      TMR6IE = TRUE;
      TMR6ON = TRUE;
      break;

      // -------------------------------------------------
    case DpaEvent_BeforeSleep:
      // Called before going to sleep	(the same handling as DpaEvent_DisableInterrupts event)
      // To minimize the power consumption, no MCU pin must be left as a digital input without defined input level value.
      //   So, unused pins in given hardware should be set as outputs:
                                // Generated by IQRF IDE according to the TR selection in a project
#if defined(TR72D)
                                // TR pin C1 (MCU pin RA0): should be set as an output
      LATA.0 = 0;                   // Low level
      TRISA.0 = 0;                  // Output

                                // TR pin C2 (MCU pin RC2): should be set as an output
      LATC.2 = 0;                   // Low level
      TRISC.2 = 0;                  // Output

                                // TR pin C5 (MCU pins RA5, RB4 and RC6 connected in parallel):
                                //   All MCU pins can be set as an input, but pin RB4 must be configured with internal pull-up (default activated).
      TRISA.5 = 1;                  // Input
      TRISB.4 = 1;                  // Input
      TRISC.6 = 1;                  // Input

                                // TR pin C6 (MCU pin RC3): should be set as an output
      LATC.3 = 0;                   // Low level
      TRISC.3 = 0;                  // Output

                                // TR pin C7 (MCU pin RC4): should be set as an output
      LATC.4 = 0;                   // Low level
      TRISC.4 = 0;                  // Output

                                // TR pin C8 (MCU pins RC5 and RC7 connected in parallel):
                                //   Only one MCU pin should be set as an output
      LATC.5 = 0;                   // Low level
      TRISC.5 = 0;                  // Output
      TRISC.7 = 1;                  // Input

#elif defined(TR76D)
                                // TR pin Q14 (MCU pin RA0): should be set as an output
      LATA.0 = 0;                   // Low level
      TRISA.0 = 0;                  // Output

                                // TR pin Q15 (MCU pin RC2): should be set as an output
      LATC.2 = 0;                   // Low level
      TRISC.2 = 0;                  // Output

                                // TR pin Q4 (MCU pin RC6): should be set as an output
      LATC.6 = 0;                   // Low level
      TRISC.6 = 0;                  // Output

                                // TR pin Q5 (MCU pin RC7): should be set as an output
      LATC.7 = 0;                   // Low level
      TRISC.7 = 0;                  // Output

                                // TR pin Q6 (MCU pin RC3): should be set as an output
      LATC.3 = 0;                   // Low level
      TRISC.3 = 0;                  // Output

                                // TR pin Q7 (MCU pin RC4): should be set as an output
      LATC.4 = 0;                   // Low level
      TRISC.4 = 0;                  // Output

                                // TR pin Q8 (MCU pin RC5): should be set as an output
      LATC.5 = 0;                   // Low level
      TRISC.5 = 0;                  // Output

                                // TR pin Q9 (MCU pin RA5): should be set as an output
      LATA.5 = 0;                   // Low level
      TRISA.5 = 0;                  // Output

                                // TR LED pins Q10 and Q11 (MCU pins RB7 and RA2) are set as outputs by OS.
                                // TR pin Q12 (MCU pin RB4) is set as an input with internal pull-up activated as default.
#else
      #warning Unsupported TR module selected.Modify the pin setting.
#endif
        // -------------------------------------------------
    case DpaEvent_DisableInterrupts:
      // Called when device needs all hardware interrupts to be disabled (before Reset, Restart, LoadCode, Remove bond, and Run RFPGM)
      // Must not use TMR6 any more
      TMR6ON = FALSE;
      TMR6IE = FALSE;
      break;
  }

  return FALSE;
}
//############################################################################################
// Default Custom DPA Handler header; 2nd include to implement Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup) 
#include "DPAcustomHandler.h"
//############################################################################################
